export const JOB_TITLE_OPTIONS = [
  { value: "CEO / Founder", label: "CEO" },
  { value: "COO", label: "COO" },
  { value: "CFO", label: "CFO" },
  { value: "CMO", label: "CMO" },
  { value: "CTO", label: "CTO" },
  { value: "VP Sales", label: "VP Sales" },
  { value: "VP Marketing", label: "VP Mktg" },
  { value: "VP Operations", label: "VP Ops" },
  { value: "Director", label: "Director" },
  { value: "Manager", label: "Mgr" },
  { value: "Sales Representative", label: "Sales Rep" },
  { value: "Account Executive", label: "AE" },
  { value: "Account Manager", label: "AM" },
  { value: "Customer Success Manager", label: "CSM" },
  { value: "Marketing Manager", label: "Mktg Mgr" },
  { value: "Operations Manager", label: "Ops Mgr" },
  { value: "Project Manager", label: "PM" },
  { value: "Product Manager", label: "PM (Product)" },
  { value: "Engineer", label: "Eng" },
  { value: "Developer", label: "Dev" },
  { value: "Designer", label: "Design" },
  { value: "Consultant", label: "Consultant" },
  { value: "Analyst", label: "Analyst" },
  { value: "Administrator", label: "Admin" },
  { value: "Support Specialist", label: "Support" },
  { value: "Other", label: "Other" },
] as const;

export const JOB_TITLES = JOB_TITLE_OPTIONS.map((o) => o.value);
